### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-wiki#11]
![image](https://user-images.githubusercontent.com/19181985/56883844-70b61600-6a9a-11e9-87e8-e94893234dd6.png)

to push to https://github.com/ExchangeUnion/xud/wiki

**Comment by sangaman** [comment]
I'm not sure I follow here, could you explain a bit more what needs to be done?

**Comment by kilrau** [comment]
Sure, before https://github.com/ExchangeUnion/xud-wiki/ had a travis integration which did [this](https://github.com/ExchangeUnion/xud-wiki/blob/master/.travis.yml) on merge to get the changes into https://github.com/ExchangeUnion/xud/wiki .

Travis integration via Github Services got deprecated, so above doesn't work anymore, so we need to set it up again via GitHub Apps.

**Comment by kilrau** [comment]
ping @sangaman

**Comment by sangaman** [comment]
Are you sure it doesn't work? I'm a bit fuzzy on the exact workings but I'm not sure that travis script depends on GitHub services, it's just a series of git commands.
